openapi: '3.0.2'
info:
  title: Masp Indexer
  version: '1.0'
servers:
  - url: https://localhost:5000/api/v1
paths:
  /block-index:
    get:
      responses:
        '200':
          description: Compressed (lossy) index of all blocks containing masp txs.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockIndexResponse'
  /health:
    get:
      responses:
        '200':
          description: OK
  /commitment-tree:
    get:
      parameters:
        - in: query
          name: height
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The commitment tree at the given height.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TreeResponse'
  /height:
    get:
      responses:
        '200':
          description: The last indexed block height.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LatestHeightResponse'
  /notes-index:
    get:
      parameters:
        - in: query
          name: height
          required: true
          schema:
            type: integer
            minimum: 0
      responses:
        '200':
          description: The notes map up to some block height.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotesIndexResponse'
  /witness-map:
    get:
      parameters:
        - in: query
          name: height
          required: true
          schema:
            type: integer
            minimum: 0
      responses:
        '200':
          description: The witness map of a specific block height.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WitnessMapResponse'
  /tx:
    get:
      parameters:
        - in: query
          name: height
          required: true
          schema:
            type: integer
            minimum: 0
        - in: query
          name: height_offset
          required: true
          schema:
            type: integer
            minimum: 0
      responses:
        '200':
          description: The masp transactions between `height` and `height + height_offset`.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TxResponse'

components:
  schemas:
    TreeResponse:
      type: object
      properties:
        commitment_tree:
          type: string
          format: byte
          description: The commitment tree bytes.
        block_height:
          type: integer
          minimum: 0
          description: The block height of the commitment tree.
    LatestHeightResponse:
      type: object
      properties:
        block_height:
          type: integer
          minimum: 0
          description: The last indexed block height.
    WitnessMapResponse:
      type: object
      properties:
        witnesses:
          type: array
          items:
            type: object
            properties:
              bytes:
                type: string
                format: byte
                description: The witness bytes.
              index:
                type: integer
                minimum: 0
                description: The witness index.
          description: The commitment tree bytes.
        block_height:
          type: integer
          minimum: 0
          description: The block height of the commitment tree.
    NotesIndexResponse:
      type: object
      properties:
        notes_index:
          type: array
          items:
            type: object
            properties:
              block_height:
                type: integer
                minimum: 0
                description: The block height containing the note.
              block_index:
                type: integer
                minimum: 0
                description: The block index containing the note.
              masp_tx_index:
                type: integer
                minimum: 0
                description: The index of the masp tx containing the note in the block.
              note_position:
                type: integer
                minimum: 0
                description: The note position in the commitment tree.
          description: The vector of notes map.
    TxResponse:
      type: object
      properties:
        txs:
          type: array
          items:
            type: object
            properties:
              block_height:
                type: integer
                minimum: 0
                description: The note block height.
              block_index:
                type: integer
                minimum: 0
                description: The index of the transaction batch in the block.
              batch:
                type: object
                properties:
                  bytes:
                    type: string
                    format: byte
                    description: The masp transaction bytes.
                  masp_tx_index:
                    type: integer
                    minimum: 0
                    description: The index of the individual masp transaction in the block.
                description: The batch of masp transactions in this slot.
          description: The vector of masp transactions.
    BlockIndexResponse:
      type: object
      properties:
        block_height:
          type: integer
          minimum: 0
          description: The block height of the index.
        index:
          description: Compressed (lossy) index of all blocks containing masp txs.
          type: object
          properties:
            seed:
              type: integer
            segment_length:
              type: integer
            segment_length_mask:
              type: integer
            segment_count_length:
              type: integer
            fingerprints:
              type: array
              items:
                type: integer
